const categories = [
    {
        name: 'home',
        label: 'About Me',
        color: '205,100%,50%,1',
        icon: 'fas fa-user',
        route: 'home',
        base: 1,
        visible: false,
        path: '/',
        image: 'undraw_onboarding_o8mv.svg',
    }, 
    {
        name: 'coding',
        label: 'Web Development',
        color: '30,100%,65%,1',
        icon: 'far fa-keyboard',
        route: 'web-development',
        base: 2,
        visible: false,
        path: '/web-development',
        image: 'undraw_report_mx0a.svg',
    }, 
    {
        name: 'photography',
        label: 'Photography',
        color: '55,75%,65%,1',
        icon: 'fas fa-camera-retro',
        route: 'photography',
        base: 3,
        visible: false,
        path: '/photography',
        image: 'undraw_organize_photos_d5nr.svg',
    }, 
    {
        name: 'video',
        label: 'Video',
        color: '205,100%,50%,1',
        icon: 'fas fa-video',
        route: 'video',
        base: 1,
        visible: false,
        path: '/video',
        image: 'undraw_celebration_0jvk.svg',
    }, 
    {
        name: 'design',
        label: 'Graphic Design',
        color: '30,100%,65%,1',
        icon: 'far fa-image',
        route: 'design',
        base: 2,
        visible: false,
        path: '/design',
        image: 'undraw_art_lover_yjfr.svg',
    }, 
];

export default categories;
